files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/SCTV1
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: F38AFEEFFBAA4953C5DA6C9A9D40394C
  logicalPath: config/SCTV1
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F38AFEEFFBAA4953C5DA6C9A9D40394C
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/SCTV1
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: F81A00E640818EDFB9E79C9BD241AEF4
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: F81A00E640818EDFB9E79C9BD241AEF4
- generatedChecksum: 13128402862922A93066D679DC3FBFC6
  logicalPath: config/SCTV1/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13128402862922A93066D679DC3FBFC6
- generatedChecksum: 8E9EE5960C0D8BED72BFAA700981C57F
  logicalPath: config/SCTV1/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8E9EE5960C0D8BED72BFAA700981C57F
- generatedChecksum: C38921098BB73406388D877133E6038F
  logicalPath: config/SCTV1/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: C38921098BB73406388D877133E6038F
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/SCTV1/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 360B57F4E6E8EF6B4BF89CD59C3B27E8
  logicalPath: config/SCTV1
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 360B57F4E6E8EF6B4BF89CD59C3B27E8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/SCTV1
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/SCTV1
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/SCTV1/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 0F9F9A01E5CDD38715225717FC322752
  logicalPath: config/SCTV1/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 0F9F9A01E5CDD38715225717FC322752
- generatedChecksum: 4EC4616DCA09DA8B724AF25F65E149C5
  logicalPath: config/SCTV1/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4EC4616DCA09DA8B724AF25F65E149C5
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/SCTV1
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: 92A3A6D5A513E30BD8649229641D245C
  logicalPath: config/SCTV1
  name: p32MK1024MCF064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 92A3A6D5A513E30BD8649229641D245C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/SCTV1;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/SCTV1;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
